import Header from '@/common/components/Header';
import useManitoGroupDetailQuery from '@/manito_group/hooks/useManitoGroupDetailQuery';
import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

const ManitoGroupPage: NextPage = () => {
  const router = useRouter();
  const { data } = useManitoGroupDetailQuery(String(router.query.groupId));
  return (
    <>
      <Head>
        <title>{`${data?.name} | Manito group page`}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className='pt-20'>
        <h1>{data?.name}</h1>
      </main>
    </>
  );
};

export default ManitoGroupPage;
