import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { NextPage } from 'next';
import { getUserAccessToken, getUserRefreshToken, setUserAccessToken } from '@/user/lib/cookie';
import ManitoGroupList from '@/manito_group/components/ManitoGroupList';

import { QueryClient, dehydrate } from '@tanstack/react-query';
import useUserInfoQuery from '@/user/hooks/useUserInfoQuery';
import { USER_INFO_QUERY_KEY } from '@/user/constant/query_key';
import { fetchGroupList } from '@/manito_group/lib/fetch';
import { MANITO_GROUP_LIST_QUERY_KEY } from '@/manito_group/constant/query_key';
import { fetchUserInfo } from '@/user/lib/fetch';
import Header from '@/common/components/Header';

const Home: NextPage = () => {
  const { data: user } = useUserInfoQuery();
  return (
    <>
      <Head>
        <title>Manito</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1>{`username: ${user?.name}`}</h1>
        <ManitoGroupList />
      </main>
    </>
  );
};

Home.getInitialProps = async ({ req, res }) => {
  let accessToken = getUserAccessToken({ req, res });
  if (!accessToken) {
    console.log('access token 재발급');
    const refreshToken = getUserRefreshToken({ req, res });
    // refresh token으로 access token 발급

    accessToken = Math.random().toString();
    setUserAccessToken(accessToken, { req, res });
  }

  // access token으로 유저정보 조회
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery([USER_INFO_QUERY_KEY], () => fetchUserInfo(accessToken));
  await queryClient.prefetchQuery([MANITO_GROUP_LIST_QUERY_KEY], () => fetchGroupList(accessToken));

  return {
    dehydratedState: dehydrate(queryClient),
  };
};

export default Home;
