import Head from 'next/head'

import { QueryClient, dehydrate } from '@tanstack/react-query'
import { GetServerSideProps, NextPage } from 'next'

import { getAccessTokenAnyway } from '@/auth/lib/jwt'
import Header from '@/common/ui/Header'
import { CreateGroup, ManitoGroupList } from '@/manito_group/ui'
import { USER_INFO_QUERY_KEY } from '@/user/constant/query_key'
import { fetchUserInfo } from '@/user/lib/fetch'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Manito</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="pt-20 flex flex-col">
                <CreateGroup />
                <ManitoGroupList />
            </main>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
    try {
        const accessToken = await getAccessTokenAnyway({ req, res })

        const queryClient = new QueryClient()
        await queryClient.prefetchQuery({
            queryKey: [USER_INFO_QUERY_KEY],
            queryFn: () => fetchUserInfo(accessToken),
        })

        return {
            props: {
                dehydratedState: dehydrate(queryClient),
            },
        }
    } catch (e) {
        console.error(e)
        return {
            props: {},
            notFound: true,
        }
    }
}
export default Home
